# Generated by Django 3.0.3 on 2020-02-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_pilot_races_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='distance_archievement_date',
            new_name='distance_achievement_date',
        ),
    ]
